# Generated by Django 5.0.7 on 2024-08-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_question_type_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='score',
        ),
        migrations.AddField(
            model_name='question',
            name='max_score',
            field=models.PositiveIntegerField(blank=True, help_text='Max score for scoring questions.', null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
